version: "3"
services:
  grafana:
    container_name: $GRAFANA_CONTAINER_NAME
    image: $GRAFANA_IMAGE
    ports:
      - "3000:3000"
    tty: true
    links:
      - influxdb1
      - influxdb2
    volumes:
      - ./config/grafana/datasources/:/etc/grafana/provisioning/datasources/
      - ./data/grafana/:/var/lib/grafana/
  influxdb1:
    container_name: $INFLUXDB_CONTAINER_NAME
    image: $INFLUXDB_IMAGE
    tty: true
    volumes:
      - ./data/influxdb1/:/var/lib/influxdb/
  influxdb2:
    container_name: interdata_influxdb2
    image: $INFLUXDB_IMAGE
    tty: true
    volumes:
      - ./data/influxdb2/:/var/lib/influxdb/
  telegraf1:
    container_name: interdata_telegraf1
    image: $TELEGRAF_IMAGE
    links:
      - influxdb1
      - influxdb2
    tty: true
    #volumes:
      #- ./config/telegraf1/telegraf.conf:/etc/telegraf/telegraf.conf