grafana:
  container_name: $GRAFANA_CONTAINER_NAME
  image: $GRAFANA_IMAGE
  ports:
    - "3000:3000"
  tty: true
  links:
    - influxdb1
  volumes:
    - ./config/grafana/datasources/:/etc/grafana/provisioning/datasources/
    - ./data/grafana/:/var/lib/grafana

influxdb1:
  container_name: $INFLUXDB_CONTAINER_NAME
  image: $INFLUXDB_IMAGE
  ports:
    - "8083:8083"
    - "8086:8086"
  tty: true