#!/bin/bash

export DOCKER_FILE  = docker-compose.yml

export BASE_IMAGE_NAME  = phusion/baseimage
export BASE_IMAGE_TAG   = 0.9.22
export BASE_IMAGE       = $(BASE_IMAGE_NAME):$(BASE_IMAGE_TAG)

export GRAFANA_DOCKERFILE       = ./docker/grafana/
export GRAFANA_CONTAINER_NAME   = interdata_grafana
export GRAFANA_IMAGE_NAME       = interdatafr/interdata-docker-grafana
export GRAFANA_IMAGE_VERSION    = 6.0.0-beta2
export GRAFANA_IMAGE            = $(GRAFANA_IMAGE_NAME):$(GRAFANA_IMAGE_VERSION)

export INFLUXDB_DOCKERFILE       = ./docker/influxdb/
export INFLUXDB_CONTAINER_NAME   = interdata_influxdb1
export INFLUXDB_IMAGE_NAME       = interdatafr/interdata-docker-influxdb
export INFLUXDB_IMAGE_VERSION    = 1.7.4
export INFLUXDB_IMAGE            = $(INFLUXDB_IMAGE_NAME):$(INFLUXDB_IMAGE_VERSION)

export TELEGRAF_DOCKERFILE       = ./docker/telegraf/
export TELEGRAF_CONTAINER_NAME   = interdata_telegraf1
export TELEGRAF_IMAGE_NAME       = interdatafr/interdata-docker-telegraf
export TELEGRAF_IMAGE_VERSION    = 1.9.5-1
export TELEGRAF_IMAGE            = $(TELEGRAF_IMAGE_NAME):$(TELEGRAF_IMAGE_VERSION)